%% ========================================================================
%  Code generated by Federico Tessari, PhD
%  Mechanical Engineering Department, MIT
%  for any question reach out to ftessari@mit.edu
%  Latest update May 7, 2026
% ========================================================================

% Press "Run" to execute the whole script and obtain all the figures and
% results of our work.
clear; clc; close all
%% ---------- Figure/graphics defaults ----------
set(0, 'DefaultLineLineWidth', 1);
set(groot,'defaultAxesFontSize',10);
set(0,'defaultfigurecolor',[1 1 1]); % white figure background
set(groot, 'defaultAxesTickLabelInterpreter','latex');
set(groot, 'defaultLegendInterpreter','latex');
set(groot,'defaultTextInterpreter','latex');

% Extra prints path if present (harmless otherwise)
addpath(genpath('Data'));

% % Source Data workbook (Nature Communications) - Commented Out as
% Source_Data.xlsx is available in GitHub
% srcFile = 'Source_Data.xlsx';
% if exist(srcFile,'file'), delete(srcFile); end
%% ---------- Labels & constants ----------
condition = {'CN','UCN'};                     % Arm configurations: 1=CN (Undesired), 2=UCN (Preferred)
task      = {'FLAT','LCK','FEX','FEXURD','ULCK'};

Nsubj = 9;                                    % Number of subjects

% Scaling Factors - The collected force and moments frome the ATI force
% sensor are in 'lbf' and 'lbf*inch', respectively.
sN = 4.44822; %[N/lbf]
sNm = 0.112985; %[Nm/lbf*inch]

%% ---------- Sampling & trimming ----------
fs   = 50;         % [Hz] (sampling frequency)
N    = 150;        % samples to save per trial
t_tot = (1/fs)*N;  % total time per trial (not used later, retained for clarity)

% Cropping indices: keep the segment [end-idx_min : end-idx_max]
idx_min = 199;  
idx_max = 50;  

%% ========================================================================
%  DATA LOADING
% ========================================================================
% Containers
MVF_i_data = cell(Nsubj,1);
MVF_f_data = cell(Nsubj,1);
MVF_tot_i  = nan(Nsubj,3);  % [subj, mean|F|, std|F|]
MVF_tot_f  = nan(Nsubj,3);

dataset    = cell(Nsubj,2,5,5); % {subj,cond,task,trial}
f_tot_med  = cell(Nsubj,2,5,5); % per-trial median |F|

for subj = 1:Nsubj
    % ---- MVF files (Pre/Post) ----
    MVF_i = importdata(sprintf('S%d_MVF_i.txt', subj));
    MVF_f = importdata(sprintf('S%d_MVF_f.txt', subj));

    MVF_i_data{subj}.data = [MVF_i.data(:,1:3)*sN, MVF_i.data(:,4:6)*sNm];
    MVF_f_data{subj}.data = [MVF_f.data(:,1:3)*sN, MVF_f.data(:,4:6)*sNm];
    
    % MVF_i_data{subj}.data = MVF_i.data;
    % MVF_f_data{subj}.data = MVF_f.data;

    % Safe cropping (same indices, clamped to data length)
    MVF_i_data{subj}.data_trim = MVF_i_data{subj}.data( ...
        max(1,end-idx_min) : max(1,end-idx_max), :);
    MVF_f_data{subj}.data_trim = MVF_f_data{subj}.data( ...
        max(1,end-idx_min) : max(1,end-idx_max), :);

    % Subject id
    MVF_tot_i(subj,1) = subj;
    MVF_tot_f(subj,1) = subj;

    % mean/std of |F|
    MVF_tot_i(subj,2) = mean(sqrt(sum(MVF_i_data{subj}.data_trim(:,1:3).^2,2)));
    MVF_tot_i(subj,3) = std( sqrt(sum(MVF_i_data{subj}.data_trim(:,1:3).^2,2)));
    MVF_tot_f(subj,2) = mean(sqrt(sum(MVF_f_data{subj}.data_trim(:,1:3).^2,2)));
    MVF_tot_f(subj,3) = std( sqrt(sum(MVF_f_data{subj}.data_trim(:,1:3).^2,2)));

    % ---- Trials ----
    for cond = 1:2
        for t = 1:5
            for trial = 1:5
                data_name = sprintf('S%d_%s_%s_T%d.txt', subj, condition{cond}, task{t}, trial);
                data_file = importdata(data_name);

                dataset{subj,cond,t,trial}.data = [data_file.data(:,1:3)*sN, data_file.data(:,4:6)*sNm];
                % dataset{subj,cond,t,trial}.data = data_file.data;
                dataset{subj,cond,t,trial}.name = data_name;

                % 3 s window from trial end: [end-idx_min : end-idx_max]
                data_trim = dataset{subj,cond,t,trial}.data( ...
                    max(1,end-idx_min) : max(1,end-idx_max), :);
                dataset{subj,cond,t,trial}.data_trim = data_trim;

                % Total force magnitude |F|
                fmag = sqrt(sum(data_trim(:,1:3).^2,2));
                f_tot_med{subj,cond,t,trial} = median(fmag);
            end
        end
    end
end

%% ========================================================================
%  Median Difference between Arm Configurations (per trial)
% ========================================================================
medianCondDiff     = [];  % CN - UCN
medianCondDiff_per = [];  % percent relative to UCN

for subj = 1:Nsubj
    for t = 1:5
        for trial = 1:5
            if (subj ~= 9 && t ~= 2)
                mCN  = f_tot_med{subj,1,t,trial};
                mUCN = f_tot_med{subj,2,t,trial};
                medianCondDiff(end+1)     = mCN - mUCN; 
                medianCondDiff_per(end+1) = 100*(mCN - mUCN)/mUCN; 
            end
        end
    end
end

%% ========================================================================
%  Pooled trials per subject/cond/task (concatenate all 5 trials)
% ========================================================================
f_tot_tr_pl = cell(Nsubj,2,5); % (subj, cond, task)

for subj = 1:Nsubj
    for cond = 1:2
        for t = 1:5
            pooled_trials = [];
            for trial = 1:5
                fmag = sqrt(sum(dataset{subj,cond,t,trial}.data_trim(:,1:3).^2,2));
                pooled_trials = [pooled_trials; fmag]; 
            end
            f_tot_tr_pl{subj,cond,t} = pooled_trials;
        end
    end
end

% Assumes: f_tot_tr_pl is Nsubj x 2 x 5 cell array
% Tasks: 1=FLAT, 2=LCK, 3=FEX, 4=URD, 5=ULCK

numTasks = 5;
numConds = 2;
rows = Nsubj * numConds;

subj_col = zeros(rows,1);
cond_col = strings(rows,1);
medians  = nan(rows, numTasks);

row = 0;
for subj = 1:Nsubj
    for cond = 1:numConds
        row = row + 1;
        subj_col(row) = subj;
        cond_col(row) = ternary(cond==1, "undesired", "preferred");
        for t = 1:numTasks
            % Exclude specific missing data (subject 9, cond=1, task=2)
            if subj == 9 && cond == 1 && t == 2
                medians(row,t) = NaN;  % mark as not available
                continue;
            end
            v = f_tot_tr_pl{subj,cond,t};
            if ~isempty(v)
                medians(row,t) = median(v, 'omitnan');
            else
                medians(row,t) = NaN;
            end
        end
    end
end

% Row-wise range (max - min across available tasks)
rowMax = max(medians, [], 2, 'omitnan');
rowMin = min(medians, [], 2, 'omitnan');
rangeCol = rowMax - rowMin;

% Percentage difference = range / max * 100
pctCol = nan(rows,1);
nonzero = rowMax > 0 & ~isnan(rowMax);
pctCol(nonzero) = (rangeCol(nonzero) ./ rowMax(nonzero)) * 100;

% Build the table
Tmed = table( ...
    subj_col, ...
    cond_col, ...
    medians(:,1), medians(:,2), medians(:,3), medians(:,4), medians(:,5), ...
    rangeCol, pctCol, ...
    'VariableNames', {'Subject','ArmCond','FLAT','LCK','FEX','URD','ULCK','Range','PctDiff'});

disp(Tmed);

% ------------------------------------------------------------------------
% Helper inline function for ternary logic
function out = ternary(cond, valTrue, valFalse)
    if cond
        out = valTrue;
    else
        out = valFalse;
    end
end

clearvars fmag data_trim data_file data_name

%% ========================================================================
%  Prepare data for boxplot/ANOVA (Pre vs Post MVF)
% ========================================================================
all_data        = [];     % concatenated magnitudes
group           = [];     % subject indices
condIPostLabels = {};     % 'Pre' or 'Post'

median_pre  = NaN(Nsubj,1);
median_post = NaN(Nsubj,1);

for subj = 1:Nsubj
    norm_i = sqrt(sum(MVF_i_data{subj}.data_trim(:,1:3).^2,2));
    norm_f = sqrt(sum(MVF_f_data{subj}.data_trim(:,1:3).^2,2));

    median_pre(subj)  = median(norm_i,'omitnan');
    median_post(subj) = median(norm_f,'omitnan');

    all_data  = [all_data; norm_i; norm_f]; %#ok<AGROW>
    nThis     = numel(norm_i) + numel(norm_f);
    group     = [group; repmat(subj, nThis, 1)]; %#ok<AGROW>
    condIPostLabels = [condIPostLabels; ...
        [repmat({'Pre'},  numel(norm_i), 1); ...
         repmat({'Post'}, numel(norm_f), 1)]]; %#ok<AGROW>
end

%% ========================================================================
%  Figure 2 (and Supplementary Figures 13..21): SINGLE SUBJECT ANALYSIS
% ========================================================================
% Task colors & legend
task_color = zeros(5,3);
task_color(1,:) = [0 0.4470 0.7410];   % FLAT
task_color(2,:) = [0.3010 0.7450 0.9330]; % LCK
task_color(3,:) = [0.4660 0.6740 0.1880]; % FEX
task_color(4,:) = [0.9290 0.6940 0.1250]; % FEXURD
task_color(5,:) = [0.8500 0.3250 0.0980]; % ULCK
task_legend = {'FLAT','LCK','FEX','URD','ULCK'}; % 'URD' label for FEXURD

for subj = 1:Nsubj
    figure('Color','white', 'Units','inches', 'Position',[1 1 7 5],'Renderer', 'painters')
    tt = tiledlayout(3,4, 'TileSpacing', 'compact', 'Padding', 'compact');
    title(tt, sprintf('Subject: %d', subj), 'FontName', 'Times New Roman', 'FontSize', 14);

    hLegend = gobjects(1, numel(task_legend));

    for cond = 1:2
        % --- Total Force panel (left col for CN, right col for UCN) ---
        if cond == 1
            axCol1 = nexttile(1,[3 1]);
        else
            axCol3 = nexttile(3,[3 1]);
        end
        hold on

        for t = 1:5
            for trial = 1:5
                f_tot = sqrt(sum(dataset{subj,cond,t,trial}.data(:,1:3).^2,2));
                h = plot(linspace(0, 7, length(f_tot)), f_tot, ...
                    'LineWidth', 1.5, 'Color', task_color(t,:));
                if trial == 1 && cond == 1
                    hLegend(t) = h;
                end
            end
        end

        ylim([0 45*sN]);
        yl = ylim;
        % Shade [3,6] s window
        fill([3 6 6 3], [yl(1) yl(1) yl(2) yl(2)], [0.5 0.5 0.5], ...
            'FaceAlpha',0.2, 'EdgeColor','none');
        plot([3 3],[yl(1) yl(2)],'k--');
        plot([6 6],[yl(1) yl(2)],'k--');

        xlabel('Time [s]'); ylabel('$F$ [N]'); box off

        % --- Fz ---
        if cond == 1
            axCol2Top = nexttile(2);
        else
            axCol4Top = nexttile(4);
        end
        hold on
        for t = 1:5
            for trial = 1:5
                fz = -dataset{subj,cond,t,trial}.data(:,3);
                plot(linspace(0,7,length(fz)), fz, 'LineWidth', 1.5, 'Color', task_color(t,:));
            end
        end
        xlabel('Time [s]'); ylabel('$F_z$ [N]'); ylim([0*sN 45*sN]); box off

        % --- Fx ---
        if cond == 1
            nexttile(6);
        else
            nexttile(8);
        end
        hold on
        for t = 1:5
            for trial = 1:5
                fx = dataset{subj,cond,t,trial}.data(:,1);
                plot(linspace(0,7,length(fx)), fx, 'LineWidth', 1.5, 'Color', task_color(t,:));
            end
        end
        xlabel('Time [s]'); ylabel('$F_x$ [N]'); ylim([-10*sN 10*sN]); box off

        % --- Fy ---
        if cond == 1
            nexttile(10);
        else
            nexttile(12);
        end
        hold on
        for t = 1:5
            for trial = 1:5
                fy = dataset{subj,cond,t,trial}.data(:,2);
                plot(linspace(0,7,length(fy)), fy, 'LineWidth', 1.5, 'Color', task_color(t,:));
            end
        end
        xlabel('Time [s]'); ylabel('$F_y$ [N]'); ylim([-10*sN 10*sN]); box off
    end

    % Legend under layout
    lgd = legend(hLegend, task_legend, 'Box','off', 'Orientation','horizontal', 'FontName','Times New Roman');
    lgd.Layout.Tile = 'south'; lgd.NumColumns = numel(task_legend);
    drawnow;

    % Column headers "(A) Undesired" / "(B) Preferred"
    p1 = axCol1.Position; p2 = axCol2Top.Position;
    p3 = axCol3.Position; p4 = axCol4Top.Position;
    xUndes = (p1(1)+p1(3)+p2(1))/2;
    xPref  = (p3(1)+p3(3)+p4(1))/2;
    yTop   = min(max([p1(2)+p1(4), p2(2)+p2(4), p3(2)+p3(4), p4(2)+p4(4)]), 0.98);

    annotation('textbox', [xUndes-0.095, yTop, 0.25, 0.03], 'String', '(A) Undesired', ...
        'HorizontalAlignment','center','VerticalAlignment','bottom', ...
        'EdgeColor','none','FontName','Times New Roman','FontSize',12);

    annotation('textbox', [xPref-0.095,  yTop, 0.25, 0.03], 'String', '(B) Preferred', ...
        'HorizontalAlignment','center','VerticalAlignment','bottom', ...
        'EdgeColor','none','FontName','Times New Roman','FontSize',12);

    % Save as true vectorial graphics with painters renderer
    % savefig(gcf, sprintf('ForceTrend_Subject%d.fig', subj));
    % exportgraphics(gcf, sprintf('ForceTrend_Subject%d.pdf', subj), 'ContentType','vector');
    % print(gcf, sprintf('ForceTrend_Subject%d.svg', subj), '-dsvg', '-painters');
end

%% ========================================================================
%  Figure 3 – Boxplots: 3x3 subjects, each with 1x2 (Undesired | Preferred)
% ========================================================================
figure('Color','white', 'Units','inches', 'Position',[0.05 0.05 7 7],'Renderer', 'painters')
tOuter = tiledlayout(3,3, 'TileSpacing','loose', 'Padding','compact');

% (Optional) store medians per subject x cond x task
medians = nan(9, 2, 5);

for subj = 1:9
    tSub = tiledlayout(tOuter, 1, 2, 'TileSpacing','compact', 'Padding','compact');
    tSub.Layout.Tile = subj;
    title(tSub, sprintf('Subject: %d', subj), 'FontName','Times New Roman');

    for cond = 1:2
        ax = nexttile(tSub, cond);
        hold(ax,'on')

        % Pooled |F| across trials for each task
        allData = cell(1,5);
        for t = 1:5
            pooledData = [];
            for trial = 1:5
                f_tot = sqrt(sum(dataset{subj,cond,t,trial}.data_trim(:,1:3).^2,2));
                pooledData = [pooledData; f_tot];
            end
            allData{t} = pooledData;
            medians(subj,cond,t) = median(pooledData,'omitnan');
        end

        boxplot(ax, cell2mat(allData), ...
            repelem(1:5, cellfun(@numel, allData)), ...
            'Colors', task_color, 'Symbol','.');

        grid(ax,'on'); box(ax,'off');
        ax.FontName = 'Times New Roman'; ax.FontSize = 10;
        xticks(ax, 1:5); xticklabels(ax, task_legend);
        ylim(ax, [0 45*sN]);

        if cond == 1
            title(ax, '(A) Undesired', 'FontName','Times New Roman');
        else
            title(ax, '(B) Preferred', 'FontName','Times New Roman');
        end
    end
    [resultsTable{subj}, anovaTable{subj}, descriptivesTable{subj}] = perform_anova_analysis(dataset, subj, 1);
end

xlabel(tOuter, 'Task Conditions', 'FontName','Times New Roman');
ylabel(tOuter, '$F$ [N]', 'Interpreter','latex', 'FontName','Times New Roman');

%% ========================================================================
%  Figure 4 – Histogram of Median Differences (CN − UCN)
% ========================================================================
figure('Color','white','Units','inches','Position',[1 1 5 3.5]);
tiledlayout(2,1)

nexttile()
histogram(medianCondDiff,'EdgeColor','none','BinWidth',1*sN); hold on
plot(median(medianCondDiff,'omitnan')*ones(1,10), linspace(0,40,10),'r--','LineWidth',2);
xlabel('$\Delta F_{med}$ [N]','FontSize',11);
ylabel('Frequency','FontSize',11);
box off

nexttile()
histogram(medianCondDiff_per,'EdgeColor','none','BinWidth',4.5); hold on
plot(median(medianCondDiff_per,'omitnan')*ones(1,10), linspace(0,35,10),'r--','LineWidth',2);
xlabel('$\Delta e_{med}$ [\%]','FontSize',11);
ylabel('Frequency','FontSize',11);
box off

%% ========================================================================
%  Figure 5 – Pre vs Post (MVF) boxplots aligned by subject
% ========================================================================
figure('Color','white','Units','inches','Position',[1 1 7 3.5],'Renderer', 'painters');

% Ensure order Pre -> Post (avoid name collision with `condition` above)
condIPostCat = categorical(condIPostLabels, {'Pre','Post'});

% Positions: for each subject, place Pre at s-0.18, Post at s+0.18
nSubj = numel(unique(group));
pos = [ (1:nSubj)-0.18 ; (1:nSubj)+0.18 ];
pos = pos(:)';
blankLabels = repmat({''}, 1, numel(pos));

boxplot(all_data, {group, condIPostCat}, ...
    'positions', pos, ...
    'labels', blankLabels, ...        % suppress boxplot's own labels
    'colors', ['k','b'], ...          % black=Pre, blue=Post
    'symbol', 'o', ...
    'plotstyle','traditional');

ax = gca;
ax.FontSize = 12;
ax.FontName = 'Times New Roman';
ax.XTick = 1:nSubj;
ax.XTickLabel = string(1:nSubj);
xlabel('Subject','FontName','Times New Roman');
ylabel('F [N]','FontName','Times New Roman');
box off

% Single legend (markers only)
hold on
h1 = plot(NaN,NaN,'sk','MarkerFaceColor','k');
h2 = plot(NaN,NaN,'sb','MarkerFaceColor','b');
legend([h1 h2], {'Pre','Post'}, 'Location','northoutside', ...
       'Orientation','horizontal', 'FontName','Times New Roman', 'Box','off');

%% ========================================================================
%  Figure 5 stats: 2-way ANOVA (Subject x Time) + post-hoc Pre vs Post
% ========================================================================
timeCat = categorical(condIPostLabels, {'Pre','Post'});
timeNum = double(timeCat);      % 1=Pre, 2=Post
subjNum = group(:);
yPP     = all_data(:);

% ---- 2-way ANOVA with interaction ----
[pPP, tblPP, ~] = anovan(yPP, {subjNum, timeNum}, ...
    'model','interaction', ...
    'varnames', {'Subject','Time'}, ...
    'display','off');

% Parse ANOVA table
hdr  = string(tblPP(1,:));
rows = strtrim(string(tblPP(2:end,1)));

colSS = find(contains(hdr,'Sum Sq','IgnoreCase',true),1);
colDF = find(contains(hdr,'d.f','IgnoreCase',true) | strcmpi(strtrim(hdr),'DF'),1);
colMS = find(contains(hdr,'Mean Sq','IgnoreCase',true),1);
colF  = find(strcmpi(strtrim(hdr),'F'),1);
colP  = find(contains(hdr,'Prob>F','IgnoreCase',true),1);

idxSubj = find(strcmpi(rows,'Subject'),1);
idxTime = find(strcmpi(rows,'Time'),1);
idxInt  = find(contains(lower(rows),'subject') & contains(lower(rows),'time') & ...
               ~strcmpi(rows,'Subject') & ~strcmpi(rows,'Time'), 1);
idxErr  = find(strcmpi(rows,'Error'),1);

factors = ["Subject"; "Time"; "Subject*Time"];
idxRows = [idxSubj; idxTime; idxInt];

SS = nan(3,1); DF = nan(3,1); MS = nan(3,1); Fv = nan(3,1); Pv = nan(3,1); etaP = nan(3,1);

SSerr = NaN;
if ~isempty(idxErr) && ~isempty(colSS)
    SSerr = local_cell2num(tblPP{idxErr+1,colSS});
end

for k = 1:3
    if isempty(idxRows(k)), continue; end
    rr = idxRows(k)+1;
    if ~isempty(colSS), SS(k) = local_cell2num(tblPP{rr,colSS}); end
    if ~isempty(colDF), DF(k) = local_cell2num(tblPP{rr,colDF}); end
    if ~isempty(colMS), MS(k) = local_cell2num(tblPP{rr,colMS}); end
    if ~isempty(colF),  Fv(k) = local_cell2num(tblPP{rr,colF});  end
    if ~isempty(colP),  Pv(k) = local_cell2num(tblPP{rr,colP});  else, Pv(k) = pPP(k); end

    if ~isnan(SS(k)) && ~isnan(SSerr) && (SS(k)+SSerr)>0
        etaP(k) = SS(k)/(SS(k)+SSerr); % partial eta^2
    end
end

ANOVA_PrePost = table(factors, SS, DF, MS, Fv, Pv, etaP, ...
    'VariableNames', {'Factor','SS','DF','MS','F','P_Value','PartialEtaSq'});

disp('=== Figure 5 ANOVA (Subject x Time) ===');
disp(ANOVA_PrePost);

% ---- Post-hoc: Pre vs Post within each subject (Bonferroni corrected) ----
alpha = 0.05;
m = Nsubj; % 9 comparisons

Subject = (1:Nsubj).';
N1_Pre = nan(Nsubj,1); N2_Post = nan(Nsubj,1);
Mean1_Pre = nan(Nsubj,1); Mean2_Post = nan(Nsubj,1);
MeanDiff_PreMinusPost = nan(Nsubj,1);
T_Statistic = nan(Nsubj,1); DF_t = nan(Nsubj,1);
CI95Bonf_Lower = nan(Nsubj,1); CI95Bonf_Upper = nan(Nsubj,1);
P_Raw = nan(Nsubj,1); P_Bonferroni = nan(Nsubj,1);
Significant = false(Nsubj,1); Cohens_d = nan(Nsubj,1);

for subj = 1:Nsubj
    xPre  = sqrt(sum(MVF_i_data{subj}.data_trim(:,1:3).^2,2));
    xPost = sqrt(sum(MVF_f_data{subj}.data_trim(:,1:3).^2,2));

    N1_Pre(subj) = numel(xPre);
    N2_Post(subj) = numel(xPost);
    Mean1_Pre(subj) = mean(xPre,'omitnan');
    Mean2_Post(subj) = mean(xPost,'omitnan');
    MeanDiff_PreMinusPost(subj) = Mean1_Pre(subj) - Mean2_Post(subj);

    [~, p0, ~, st] = ttest2(xPre, xPost, 'Tail','both', 'Vartype','equal', 'Alpha',alpha);
    [~, ~, ciB]    = ttest2(xPre, xPost, 'Tail','both', 'Vartype','equal', 'Alpha',alpha/m);

    P_Raw(subj) = p0;
    P_Bonferroni(subj) = min(p0*m, 1);
    Significant(subj) = P_Bonferroni(subj) < alpha;

    T_Statistic(subj) = st.tstat;
    DF_t(subj) = st.df;
    CI95Bonf_Lower(subj) = ciB(1);
    CI95Bonf_Upper(subj) = ciB(2);

    Cohens_d(subj) = local_cohens_d(xPre, xPost);
end

PostHoc_PrePost = table(Subject, N1_Pre, N2_Post, Mean1_Pre, Mean2_Post, MeanDiff_PreMinusPost, ...
    T_Statistic, DF_t, CI95Bonf_Lower, CI95Bonf_Upper, P_Raw, P_Bonferroni, Significant, Cohens_d, ...
    'VariableNames', {'Subject','N1_Pre','N2_Post','Mean1_Pre','Mean2_Post','MeanDiff_PreMinusPost', ...
                      'T_Statistic','DF','CI95Bonf_Lower','CI95Bonf_Upper','P_Raw','P_Bonferroni','Significant','Cohens_d'});

disp('=== Figure 5 Post-hoc (Pre vs Post within subject) ===');
disp(PostHoc_PrePost);

% Optional export
% writetable(ANOVA_PrePost, 'Figure5_PrePost_Stats.xlsx', 'Sheet', 'ANOVA');
% writetable(PostHoc_PrePost, 'Figure5_PrePost_Stats.xlsx', 'Sheet', 'PostHoc');

%% ========================================================================
%  Figure 22 – Boxplots: 3x3 subjects, each with 1x2 (Undesired | Preferred)
%  using only Fz
% ========================================================================
figure('Color','white', 'Units','inches', 'Position',[0.05 0.05 7 7],'Renderer', 'painters')
tOuter = tiledlayout(3,3, 'TileSpacing','loose', 'Padding','compact');

% (Optional) store medians per subject x cond x task
medians = nan(9, 2, 5);

for subj = 1:9
    tSub = tiledlayout(tOuter, 1, 2, 'TileSpacing','compact', 'Padding','compact');
    tSub.Layout.Tile = subj;
    title(tSub, sprintf('Subject: %d', subj), 'FontName','Times New Roman');

    for cond = 1:2
        ax = nexttile(tSub, cond);
        hold(ax,'on')

        % Pooled |F| across trials for each task
        allData = cell(1,5);
        for t = 1:5
            pooledData = [];
            for trial = 1:5
                f_tot = -dataset{subj,cond,t,trial}.data_trim(:,3);
                pooledData = [pooledData; f_tot];
            end
            allData{t} = pooledData;
            medians(subj,cond,t) = median(pooledData,'omitnan');
        end

        boxplot(ax, cell2mat(allData), ...
            repelem(1:5, cellfun(@numel, allData)), ...
            'Colors', task_color, 'Symbol','.');

        grid(ax,'on'); box(ax,'off');
        ax.FontName = 'Times New Roman'; ax.FontSize = 10;
        xticks(ax, 1:5); xticklabels(ax, task_legend);
        ylim(ax, [0 45*sN]);

        if cond == 1
            title(ax, '(A) Undesired', 'FontName','Times New Roman');
        else
            title(ax, '(B) Preferred', 'FontName','Times New Roman');
        end
    end
    resultsTable_Fz{subj} = perform_anova_analysis(dataset, subj, 2); %This table contains the results of the statistical analysis for each subject
end

xlabel(tOuter, 'Task Conditions', 'FontName','Times New Roman');
ylabel(tOuter, '$F$ [N]', 'Interpreter','latex', 'FontName','Times New Roman');
%% ========================================================================
%  Figure EXTRA – Boxplots: 3x3 subjects, each with 1x2 (Undesired |
%  Preferred) using only the means of each time window rather all the
%  samples
% ========================================================================
figure('Color','white', 'Units','inches', 'Position',[0.05 0.05 7 7],'Renderer', 'painters')
tOuter = tiledlayout(3,3, 'TileSpacing','loose', 'Padding','compact');

% (Optional) store medians per subject x cond x task
medians = nan(9, 2, 5);

for subj = 1:9
    tSub = tiledlayout(tOuter, 1, 2, 'TileSpacing','compact', 'Padding','compact');
    tSub.Layout.Tile = subj;
    title(tSub, sprintf('Subject: %d', subj), 'FontName','Times New Roman');

    for cond = 1:2
        ax = nexttile(tSub, cond);
        hold(ax,'on')

        % Pooled |F| across trials for each task
        allData = cell(1,5);
        for t = 1:5
            pooledData = [];
            for trial = 1:5
                f_tot = mean(sqrt(sum(dataset{subj,cond,t,trial}.data_trim(:,1:3).^2,2)));
                pooledData = [pooledData; f_tot];
            end
            allData{t} = pooledData;
            medians(subj,cond,t) = median(pooledData,'omitnan');
        end

        boxplot(ax, cell2mat(allData), ...
            repelem(1:5, cellfun(@numel, allData)), ...
            'Colors', task_color, 'Symbol','.');

        grid(ax,'on'); box(ax,'off');
        ax.FontName = 'Times New Roman'; ax.FontSize = 10;
        xticks(ax, 1:5); xticklabels(ax, task_legend);
        ylim(ax, [0 45*sN]);

        if cond == 1
            title(ax, '(A) Undesired', 'FontName','Times New Roman');
        else
            title(ax, '(B) Preferred', 'FontName','Times New Roman');
        end
    end
    resultsTable_med{subj} = perform_anova_analysis(dataset, subj, 3); %This table contains the results of the statistical analysis for each subject
end

xlabel(tOuter, 'Task Conditions', 'FontName','Times New Roman');
ylabel(tOuter, '$F$ [N]', 'Interpreter','latex', 'FontName','Times New Roman');
%% ========================================================================
%  SOURCE DATA EXPORT (Nature Communications) - Commented Out As
%  Source_Data.xlsx is available on GitHub
% ========================================================================
% task_lbl = {'FLAT','LCK','FEX','URD','ULCK'};
% 
% % -------- Figure 2 (ONLY subject 6) --------
% SD2 = table;
% subj = 6;
% for cond = 1:2
%     for t = 1:5
%         for trial = 1:5
%             X = dataset{subj,cond,t,trial}.data;   % full 7 s trace
%             n = size(X,1);
%             time_s = linspace(0,7,n).';
%             Fmag = sqrt(sum(X(:,1:3).^2,2));
% 
%             SD2 = [SD2; table( ...
%                 repmat(subj,n,1), repmat({condition{cond}},n,1), repmat({task{t}},n,1), repmat(trial,n,1), ...
%                 time_s, X(:,1), X(:,2), X(:,3), Fmag, ...
%                 'VariableNames', {'Subject','Condition','Task','Trial','Time_s','Fx_N','Fy_N','Fz_N','Fmag_N'})]; %#ok<AGROW>
%         end
%     end
% end
% writetable(SD2, srcFile, 'Sheet', 'Figure2');
% 
% % -------- Supplementary Figures 13–21 (all subjects except 6) --------
% SDsupp = table;
% for subj = 1:Nsubj
%     if subj == 6, continue; end
%     suppFigNum = 12 + subj;  % S1->13, ..., S9->21 (subject 6 would be 18)
% 
%     for cond = 1:2
%         for t = 1:5
%             for trial = 1:5
%                 X = dataset{subj,cond,t,trial}.data;
%                 n = size(X,1);
%                 time_s = linspace(0,7,n).';
%                 Fmag = sqrt(sum(X(:,1:3).^2,2));
% 
%                 SDsupp = [SDsupp; table( ...
%                     repmat(suppFigNum,n,1), repmat(subj,n,1), ...
%                     repmat({condition{cond}},n,1), repmat({task{t}},n,1), repmat(trial,n,1), ...
%                     time_s, X(:,1), X(:,2), X(:,3), Fmag, ...
%                     'VariableNames', {'SuppFigure','Subject','Condition','Task','Trial','Time_s','Fx_N','Fy_N','Fz_N','Fmag_N'})]; %#ok<AGROW>
%             end
%         end
%     end
% end
% writetable(SDsupp, srcFile, 'Sheet', 'SuppFig13_21');
% 
% % -------- Figure 3 (boxplot source values: pooled |F|) --------
% SD3 = table;
% for subj = 1:Nsubj
%     for cond = 1:2
%         for t = 1:5
%             v = f_tot_tr_pl{subj,cond,t};
%             n = numel(v);
%             SD3 = [SD3; table( ...
%                 repmat(subj,n,1), repmat({condition{cond}},n,1), repmat({task_lbl{t}},n,1), (1:n)', v(:), ...
%                 'VariableNames', {'Subject','Condition','Task','Sample','Fmag_N'})]; %#ok<AGROW>
%         end
%     end
% end
% writetable(SD3, srcFile, 'Sheet', 'Figure3');
% 
% % -------- Figure 4 (histogram inputs) --------
% SD4 = table(medianCondDiff(:), medianCondDiff_per(:), ...
%     'VariableNames', {'DeltaFmed_CN_minus_UCN_N','DeltaMedianPercent_CN_minus_UCN'});
% writetable(SD4, srcFile, 'Sheet', 'Figure4');
% 
% % -------- Figure 5 (Pre/Post MVF boxplot inputs) --------
% SD5 = table(group(:), condIPostLabels(:), all_data(:), ...
%     'VariableNames', {'Subject','Session','Fmag_N'});
% writetable(SD5, srcFile, 'Sheet', 'Figure5');
% 
% % -------- Figure 22 (Fz boxplot source values) --------
% SD22 = table;
% for subj = 1:Nsubj
%     for cond = 1:2
%         for t = 1:5
%             pooledFz = [];
%             for trial = 1:5
%                 pooledFz = [pooledFz; -dataset{subj,cond,t,trial}.data_trim(:,3)]; %#ok<AGROW>
%             end
%             n = numel(pooledFz);
%             SD22 = [SD22; table( ...
%                 repmat(subj,n,1), repmat({condition{cond}},n,1), repmat({task_lbl{t}},n,1), (1:n)', pooledFz(:), ...
%                 'VariableNames', {'Subject','Condition','Task','Sample','Fz_N'})]; %#ok<AGROW>
%         end
%     end
% end
% writetable(SD22, srcFile, 'Sheet', 'Figure22');
% 
% fprintf('\nSource data file created: %s\n', srcFile);
%% ========================================================================
%  LOCAL FUNCTIONS – used by perform_anova_analysis
% ========================================================================

function [posthocTable, anovaTable, descriptivesTable] = perform_anova_analysis(dataset, subj, flag)
    % Subject-level 2-way ANOVA (Condition x Task) + Bonferroni post hoc.
    % Outputs:
    %   posthocTable      -> pairwise comparisons with t, df, CI, p, effect size
    %   anovaTable        -> ANOVA factors with SS, df, MS, F, p, partial eta^2
    %   descriptivesTable -> per cell summary stats (n, mean, SD, SEM, median, IQR, min, max)

    task_labels = {'FLAT', 'LCK', 'FEX', 'FEXURD', 'ULCK'};
    cond_labels = {'CN', 'UCN'};
    alpha = 0.05;

    switch flag
        case 1, metricLabel = "Fmag";
        case 2, metricLabel = "Fz";
        case 3, metricLabel = "TrialMeanFmag";
        otherwise, metricLabel = "Unknown";
    end

    allData   = [];
    groupCond = [];
    groupTask = [];
    data_map  = containers.Map(); % key: 'CN_FLAT', etc.

    % -------- Build pooled data and descriptives --------
    desc_subj = [];
    desc_metric = strings(0,1);
    desc_cond = strings(0,1);
    desc_task = strings(0,1);
    desc_n = [];
    desc_mean = []; desc_sd = []; desc_sem = [];
    desc_median = []; desc_iqr = []; desc_min = []; desc_max = [];

    numCond = 2; numTask = 5; numTrials = 5;

    for cond = 1:numCond
        for t = 1:numTask
            pooledData = [];

            for trial = 1:numTrials
                D = dataset{subj,cond,t,trial};
                if isempty(D) || ~isfield(D,'data_trim') || isempty(D.data_trim)
                    continue
                end

                if flag == 1
                    f_tot = sqrt(sum(D.data_trim(:,1:3).^2,2));
                elseif flag == 2
                    f_tot = -D.data_trim(:,3);
                elseif flag == 3
                    f_tot = mean(sqrt(sum(D.data_trim(:,1:3).^2,2))); % one value per trial
                else
                    f_tot = [];
                end

                pooledData = [pooledData; f_tot(:)]; %#ok<AGROW>
            end

            pooledData = pooledData(~isnan(pooledData));
            key = sprintf('%s_%s', cond_labels{cond}, task_labels{t});
            data_map(key) = pooledData;

            if ~isempty(pooledData)
                allData   = [allData; pooledData]; %#ok<AGROW>
                groupCond = [groupCond; repmat(cond, numel(pooledData), 1)]; %#ok<AGROW>
                groupTask = [groupTask; repmat(t,    numel(pooledData), 1)]; %#ok<AGROW>
            end

            % descriptives (always create row)
            n = numel(pooledData);
            if n > 0
                mu = mean(pooledData,'omitnan');
                sdv = std(pooledData,0,'omitnan');
                semv = sdv / sqrt(n);
                medv = median(pooledData,'omitnan');
                iqrv = iqr(pooledData);
                mnv = min(pooledData);
                mxv = max(pooledData);
            else
                mu = NaN; sdv = NaN; semv = NaN; medv = NaN; iqrv = NaN; mnv = NaN; mxv = NaN;
            end

            desc_subj(end+1,1)   = subj; %#ok<AGROW>
            desc_metric(end+1,1) = metricLabel; %#ok<AGROW>
            desc_cond(end+1,1)   = string(cond_labels{cond}); %#ok<AGROW>
            desc_task(end+1,1)   = string(task_labels{t}); %#ok<AGROW>
            desc_n(end+1,1)      = n; %#ok<AGROW>
            desc_mean(end+1,1)   = mu; %#ok<AGROW>
            desc_sd(end+1,1)     = sdv; %#ok<AGROW>
            desc_sem(end+1,1)    = semv; %#ok<AGROW>
            desc_median(end+1,1) = medv; %#ok<AGROW>
            desc_iqr(end+1,1)    = iqrv; %#ok<AGROW>
            desc_min(end+1,1)    = mnv; %#ok<AGROW>
            desc_max(end+1,1)    = mxv; %#ok<AGROW>
        end
    end

    descriptivesTable = table(desc_subj, desc_metric, desc_cond, desc_task, ...
        desc_n, desc_mean, desc_sd, desc_sem, desc_median, desc_iqr, desc_min, desc_max, ...
        'VariableNames', {'Subject','Metric','Condition','Task','N','Mean','SD','SEM','Median','IQR','Min','Max'});

    % -------- ANOVA --------
    if isempty(allData) || numel(unique(groupCond)) < 2 || numel(unique(groupTask)) < 2
        anovaTable = table;
    else
        [p, tbl, stats] = anovan(allData, {groupCond, groupTask}, ...
            'model','interaction', 'varnames', {'Condition','Task'}, 'display','off'); %#ok<ASGLU>

        headers = string(tbl(1,:));
        rowNames = string(tbl(2:end,1)); rowNames = strtrim(rowNames);

        colSS = find(contains(headers,'Sum Sq','IgnoreCase',true),1);
        colDF = find(contains(headers,'d.f','IgnoreCase',true) | strcmpi(strtrim(headers),'DF'),1);
        colMS = find(contains(headers,'Mean Sq','IgnoreCase',true),1);
        colF  = find(strcmpi(strtrim(headers),'F'),1);
        if isempty(colF), colF = find(contains(headers,'F','IgnoreCase',true),1); end
        colP  = find(contains(headers,'Prob>F','IgnoreCase',true),1);

        idxCond = find(strcmpi(rowNames,'Condition'),1);
        idxTask = find(strcmpi(rowNames,'Task'),1);
        idxInter = find(contains(lower(rowNames),'condition') & contains(lower(rowNames),'task') ...
                     & ~strcmpi(rowNames,'Condition') & ~strcmpi(rowNames,'Task'),1);
        idxErr = find(strcmpi(rowNames,'Error'),1);

        SS_error = NaN;
        if ~isempty(idxErr) && ~isempty(colSS)
            SS_error = local_cell2num(tbl{idxErr+1,colSS});
        end

        factors = {'Condition'; 'Task'; 'Condition*Task'};
        idxRows = [idxCond; idxTask; idxInter];

        SS = nan(3,1); DF = nan(3,1); MS = nan(3,1); Fv = nan(3,1); Pv = nan(3,1); etaP = nan(3,1);
        for k = 1:3
            r = idxRows(k);
            if isempty(r), continue; end
            rr = r + 1; % tbl has header row

            if ~isempty(colSS), SS(k) = local_cell2num(tbl{rr,colSS}); end
            if ~isempty(colDF), DF(k) = local_cell2num(tbl{rr,colDF}); end
            if ~isempty(colMS), MS(k) = local_cell2num(tbl{rr,colMS}); end
            if ~isempty(colF),  Fv(k) = local_cell2num(tbl{rr,colF});  end
            if ~isempty(colP),  Pv(k) = local_cell2num(tbl{rr,colP});  else, Pv(k) = p(k); end

            if ~isnan(SS(k)) && ~isnan(SS_error) && (SS(k)+SS_error)>0
                etaP(k) = SS(k)/(SS(k)+SS_error); % partial eta^2
            end
        end

        anovaTable = table( ...
            repmat(subj,3,1), repmat(metricLabel,3,1), string(factors), ...
            SS, DF, MS, Fv, Pv, etaP, ...
            'VariableNames', {'Subject','Metric','Factor','SS','DF','MS','F','P_Value','PartialEtaSq'});
    end

    % -------- Build list of requested post hoc comparisons --------
    % 1) same condition, different task
    C = []; % [cond1 task1 cond2 task2]
    cmpType = strings(0,1);

    for cond = 1:2
        for t1 = 1:4
            for t2 = t1+1:5
                C(end+1,:) = [cond t1 cond t2]; %#ok<AGROW>
                cmpType(end+1,1) = "WithinCondition"; %#ok<AGROW>
            end
        end
    end

    % 2) same task, different condition (CN vs UCN)
    for t = 1:5
        C(end+1,:) = [1 t 2 t]; %#ok<AGROW>
        cmpType(end+1,1) = "BetweenCondition"; %#ok<AGROW>
    end

    nCmp = size(C,1);

    % determine available comparisons for Bonferroni m
    available = false(nCmp,1);
    for i = 1:nCmp
        c1 = C(i,1); t1 = C(i,2); c2 = C(i,3); t2 = C(i,4);
        k1 = sprintf('%s_%s', cond_labels{c1}, task_labels{t1});
        k2 = sprintf('%s_%s', cond_labels{c2}, task_labels{t2});
        if isKey(data_map,k1) && isKey(data_map,k2)
            x = data_map(k1); y = data_map(k2);
            available(i) = numel(x)>=2 && numel(y)>=2;
        end
    end
    m = sum(available); % number of tests actually performed
    if m == 0, m = 1; end

    % -------- Post hoc table --------
    Group1 = strings(nCmp,1);
    Group2 = strings(nCmp,1);
    N1 = nan(nCmp,1); N2 = nan(nCmp,1);
    Mean1 = nan(nCmp,1); Mean2 = nan(nCmp,1);
    MeanDiff = nan(nCmp,1);
    T_stat = nan(nCmp,1); DF_t = nan(nCmp,1);
    CI95_L = nan(nCmp,1); CI95_U = nan(nCmp,1);
    CI95Bonf_L = nan(nCmp,1); CI95Bonf_U = nan(nCmp,1);
    P_raw = nan(nCmp,1); P_bonf = nan(nCmp,1);
    Significant = false(nCmp,1);
    Cohens_d = nan(nCmp,1);
    DataAvailable = false(nCmp,1);

    for i = 1:nCmp
        c1 = C(i,1); t1 = C(i,2); c2 = C(i,3); t2 = C(i,4);

        Group1(i) = sprintf('%s - %s', cond_labels{c1}, task_labels{t1});
        Group2(i) = sprintf('%s - %s', cond_labels{c2}, task_labels{t2});

        k1 = sprintf('%s_%s', cond_labels{c1}, task_labels{t1});
        k2 = sprintf('%s_%s', cond_labels{c2}, task_labels{t2});
        if ~(isKey(data_map,k1) && isKey(data_map,k2)), continue; end

        x = data_map(k1); y = data_map(k2);
        x = x(~isnan(x)); y = y(~isnan(y));

        N1(i) = numel(x); N2(i) = numel(y);
        Mean1(i) = mean(x,'omitnan');
        Mean2(i) = mean(y,'omitnan');
        MeanDiff(i) = Mean1(i) - Mean2(i);

        if numel(x) < 2 || numel(y) < 2
            continue
        end

        DataAvailable(i) = true;

        % two-sided t-test (equal variances, consistent with ANOVA-style pooling)
        [~, p0, ci0, st0] = ttest2(x, y, 'Tail','both', 'Vartype','equal', 'Alpha',alpha);
        [~, ~, ciB, ~]    = ttest2(x, y, 'Tail','both', 'Vartype','equal', 'Alpha',alpha/m);

        P_raw(i)   = p0;
        P_bonf(i)  = min(p0*m, 1);
        Significant(i) = P_bonf(i) < alpha;

        T_stat(i) = st0.tstat;
        DF_t(i)   = st0.df;
        CI95_L(i) = ci0(1); CI95_U(i) = ci0(2);
        CI95Bonf_L(i) = ciB(1); CI95Bonf_U(i) = ciB(2);

        Cohens_d(i) = local_cohens_d(x, y);
    end

    posthocTable = table( ...
        repmat(subj,nCmp,1), repmat(metricLabel,nCmp,1), cmpType, ...
        Group1, Group2, DataAvailable, ...
        N1, N2, Mean1, Mean2, MeanDiff, ...
        T_stat, DF_t, ...
        CI95_L, CI95_U, CI95Bonf_L, CI95Bonf_U, ...
        P_raw, P_bonf, Significant, Cohens_d, ...
        'VariableNames', {'Subject','Metric','ComparisonType','Group1','Group2','DataAvailable', ...
                          'N1','N2','Mean1','Mean2','MeanDiff', ...
                          'T_Statistic','DF','CI95_Lower','CI95_Upper','CI95Bonf_Lower','CI95Bonf_Upper', ...
                          'P_Raw','P_Bonferroni','Significant','Cohens_d'});
end

function v = local_cell2num(x)
    if isnumeric(x)
        v = x;
    elseif isstring(x) || ischar(x)
        v = str2double(x);
    else
        v = NaN;
    end
end

function d = local_cohens_d(x, y)
    % Try robust Cohen's d if meanEffectSize is available; else classic d.
    d = NaN;
    try
        if exist('meanEffectSize','file') == 2
            T = meanEffectSize(x, y, Effect="robustcohen");
            d = T.Effect;
            return;
        end
    catch
        % fall through to classic d
    end
    % classic pooled SD Cohen's d
    x = x(~isnan(x)); y = y(~isnan(y));
    nx = numel(x); ny = numel(y);
    sx = std(x,0);   sy = std(y,0);
    sp = sqrt(((nx-1)*sx^2 + (ny-1)*sy^2) / (nx+ny-2));
    d  = (mean(x) - mean(y)) / sp;
end
